[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="hessym"
version="2025.0.0"

[tool.pytest.ini_options]
filterwarnings="ignore::DeprecationWarning"